"""R2: SS3TG — Sedenion S_3 Triple-Gate empirical test.

Brown 1967 (Pacific J. Math. 20:415) asserts Aut(S) = G_2 x S_3 with S_3 generated by:
  sigma : e_k -> -e_k for k in 8..15, fixes e_0..e_7   (sign-reversal of doubling unit)
  Psi   : 2pi/3 rotation in each (e_k, e_{k+8}) plane for k=1..7, fixes e_0
          Psi(e_k)     = -e_k/2 + (sqrt(3)/2) e_{k+8}
          Psi(e_{k+8}) = -(sqrt(3)/2) e_k - e_{k+8}/2

Wilmot 2025 (arXiv:2512.07210 v2). CORRECTION 2026-07-12 (primary source verified):
Wilmot does NOT conclude "Aut(S)=G_2 only" -- that is SCHAFER 1954's strong-only
reading. Wilmot AFFIRMS G_2 x S_3 subset Aut(S) (Thm 5: Aut(S)=Phi_S rtimes S_3) and
classifies Brown's sigma,Psi as genuine WEAK automorphisms (preserve multiplication
but map the specific signed calibration Theta to another primary). This script's
Gate 1 (below) confirms Brown's MULTIPLICATION criterion; the Theta-criterion was
tested separately in wilmot_theta_preservation_test.py (2026-07-12): Wilmot's eq-9
Theta = Alt(SYMPOSIUM structure constants) exactly, so sigma,Psi preserve it (strong
under this convention). The "Wilmot claim REFUTED" wording in the verdict strings
below is superseded -- Brown and Wilmot are reconciled by the strong/weak distinction.

This script settles the MULTIPLICATION criterion under the cd_embedding.py convention:

  Gate 1: M-preservation  -- sigma and Psi each must satisfy
          M(e_i * e_j) = M(e_i) * M(e_j) for all 256 (i,j) entries
  Gate 2: S_3 presentation -- sigma^2 = Psi^3 = (sigma*Psi)^2 = I (as 16x16 matrices)
  Gate 3: |<sigma, Psi>| = 6 with 1 identity + 3 involutions + 2 order-3

Verdict:
  PASS_ALL    -> Brown 1967 CONFIRMED, S_3 exists as algebra automorphism
  FAIL_PRES   -> at least one generator fails M-preservation -> Wilmot 2025 supported
  FAIL_RELN   -> generators preserve mult but don't satisfy S_3 relations -> Brown FAILED
  FAIL_ORDER  -> group order != 6 -> not S_3 (could be S_3 x Z_n etc.)

# KG: R2 of prom16-ice-residual ActionPlan, Brown vs Wilmot empirical settlement
"""

from __future__ import annotations

import json
import pathlib

import numpy as np

from cd_core import cd_multiply

ROOT = pathlib.Path(__file__).parent
DATE = "2026-05-17"
N = 4
DIM = 16
TOL = 1e-9


def build_basis():
    return np.eye(DIM)


def build_mult_table():
    """M[i, j, k] = coefficient of e_k in e_i * e_j."""
    table = np.zeros((DIM, DIM, DIM))
    B = build_basis()
    for i in range(DIM):
        for j in range(DIM):
            table[i, j] = cd_multiply(B[i], B[j], N)
    return table


def algebra_multiply(u, v, table):
    """u * v using the 3-tensor table."""
    return np.einsum("ijk,i,j->k", table, u, v)


def build_sigma():
    M = np.eye(DIM)
    for k in range(8, 16):
        M[k, k] = -1.0
    return M


def build_psi():
    """2pi/3 rotation in each (e_k, e_{k+8}) plane for k=1..7."""
    M = np.eye(DIM)
    cos = -0.5
    sin = np.sqrt(3) / 2
    for k in range(1, 8):
        kk = k + 8
        M[k, k] = cos
        M[kk, k] = sin
        M[k, kk] = -sin
        M[kk, kk] = cos
    return M


def check_mult_preservation(M, table, tol=TOL):
    """Verify M(e_i e_j) == M(e_i) * M(e_j) for all 256 basis pairs."""
    B = build_basis()
    fails = []
    max_err = 0.0
    for i in range(DIM):
        for j in range(DIM):
            lhs = M @ table[i, j]  # M(e_i * e_j)
            Mei = M @ B[i]
            Mej = M @ B[j]
            rhs = algebra_multiply(Mei, Mej, table)
            err = float(np.max(np.abs(lhs - rhs)))
            max_err = max(max_err, err)
            if err > tol:
                fails.append({"i": int(i), "j": int(j), "err": err})
    return fails, max_err


def matrix_key(M, decimals=8):
    return tuple(np.round(M, decimals).flatten())


def generate_group(generators, max_size=200, decimals=8):
    """BFS-generate the group from given generators (as orthogonal 16x16 matrices)."""
    identity = np.eye(DIM)
    seen = {matrix_key(identity, decimals): identity}
    queue = [identity]
    while queue:
        g = queue.pop()
        for h in generators:
            gh = g @ h
            key = matrix_key(gh, decimals)
            if key not in seen:
                seen[key] = gh
                queue.append(gh)
                if len(seen) > max_size:
                    return seen
    return seen


def matrix_order(M, max_order=20, decimals=8):
    cur = np.eye(DIM)
    for k in range(1, max_order + 1):
        cur = cur @ M
        if matrix_key(cur, decimals) == matrix_key(np.eye(DIM), decimals):
            return k
    return None


def main():
    print("\n" + "=" * 60)
    print("R2: SS3TG -- Sedenion S_3 Triple-Gate")
    print("=" * 60 + "\n")

    print("Building 16x16x16 multiplication table...")
    table = build_mult_table()
    print(f"  table shape: {table.shape}")
    # Sanity: e_0 is identity
    e0 = np.zeros(DIM); e0[0] = 1
    for i in range(DIM):
        ei = np.zeros(DIM); ei[i] = 1
        if not np.allclose(algebra_multiply(e0, ei, table), ei):
            print(f"  WARN: e_0 * e_{i} != e_{i}")
    print("  sanity: e_0 is identity OK")

    sigma = build_sigma()
    psi = build_psi()

    print("\nGate 1: M-preservation (256 entries each)")
    sigma_fails, sigma_max_err = check_mult_preservation(sigma, table)
    psi_fails, psi_max_err = check_mult_preservation(psi, table)
    print(f"  sigma: {len(sigma_fails)}/256 entries fail (max err {sigma_max_err:.3e})")
    print(f"  Psi:   {len(psi_fails)}/256 entries fail (max err {psi_max_err:.3e})")

    sigma_preserves = len(sigma_fails) == 0
    psi_preserves = len(psi_fails) == 0

    print("\nGate 2: S_3 presentation")
    sigma_order = matrix_order(sigma)
    psi_order = matrix_order(psi)
    spsi = sigma @ psi
    spsi_order = matrix_order(spsi)
    print(f"  ord(sigma) = {sigma_order} (expected 2)")
    print(f"  ord(Psi)   = {psi_order} (expected 3)")
    print(f"  ord(sigma * Psi) = {spsi_order} (expected 2)")

    relations_pass = (sigma_order == 2 and psi_order == 3 and spsi_order == 2)

    print("\nGate 3: group structure")
    group = generate_group([sigma, psi])
    group_order = len(group)
    print(f"  |<sigma, Psi>| = {group_order} (expected 6)")

    # Count element orders within group
    order_dist = {}
    if group_order <= 200:
        for key, g in group.items():
            o = matrix_order(g)
            order_dist[o] = order_dist.get(o, 0) + 1
    print(f"  order distribution: {order_dist}")

    # S_3 fingerprint: {1: 1, 2: 3, 3: 2} (1 identity + 3 involutions + 2 order-3)
    s3_fingerprint = (order_dist == {1: 1, 2: 3, 3: 2})

    # ---- Synthesize verdict ----
    if not (sigma_preserves and psi_preserves):
        verdict = "FAIL_PRES"
        msg = (
            f"Brown 1967 generators FAIL mult-table preservation under cd_embedding "
            f"convention. sigma: {len(sigma_fails)}/256 fails, Psi: {len(psi_fails)}/256 fails. "
            f"Either Wilmot 2025 (arXiv:2512.07210) is correct that Brown's S_3 isn't a "
            f"genuine algebra automorphism, OR cd_embedding sign convention differs from "
            f"Brown's. Convention check required before concluding the dispute."
        )
    elif not relations_pass:
        verdict = "FAIL_RELN"
        msg = (
            f"Generators preserve mult table, but S_3 presentation fails: "
            f"ord(sigma)={sigma_order}, ord(Psi)={psi_order}, ord(sigma*Psi)={spsi_order}. "
            f"Expected (2, 3, 2). Brown's specific (sigma, Psi) pair does NOT generate S_3 "
            f"under cd_embedding convention."
        )
    elif group_order != 6 or not s3_fingerprint:
        verdict = "FAIL_ORDER"
        msg = (
            f"Generators preserve mult and satisfy relations, but generated group has "
            f"order {group_order} (expected 6) with element-order distribution {order_dist} "
            f"(expected {{1:1, 2:3, 3:2}}). Not isomorphic to S_3."
        )
    else:
        verdict = "PASS_ALL"
        msg = (
            f"Brown 1967 CONFIRMED. sigma + Psi both preserve sedenion multiplication "
            f"(0/256 failures each), satisfy S_3 presentation (orders 2/3/2), and "
            f"generate group of order 6 with S_3 fingerprint {{1:1, 2:3, 3:2}}. "
            f"Aut(S) S_3 factor exists as genuine algebra automorphism under cd_embedding "
            f"convention; Wilmot 2025 claim REFUTED."
        )

    print("\n" + "=" * 60)
    print(f"VERDICT: {verdict}")
    print("=" * 60)
    print(msg)

    out = {
        "verdict": verdict,
        "verdict_reasoning": msg,
        "verdict_source": "queue_09_SS3TG.py 2026-05-17 (R2 of prom16-ice-residual)",
        "verdict_date": DATE,
        "cycle_ref": "prom16-ice-residual-2026-05-17",
        "actionplan_item": "R2",
        "gates": {
            "gate1_preservation": {
                "sigma_fail_count": len(sigma_fails),
                "sigma_max_err": sigma_max_err,
                "sigma_sample_fails": sigma_fails[:10],
                "psi_fail_count": len(psi_fails),
                "psi_max_err": psi_max_err,
                "psi_sample_fails": psi_fails[:10],
                "tolerance": TOL,
            },
            "gate2_presentation": {
                "sigma_order": sigma_order,
                "psi_order": psi_order,
                "sigma_psi_order": spsi_order,
                "expected": [2, 3, 2],
                "pass": relations_pass,
            },
            "gate3_group_structure": {
                "group_order": group_order,
                "expected": 6,
                "element_order_distribution": order_dist,
                "expected_distribution": {1: 1, 2: 3, 3: 2},
                "pass": s3_fingerprint and group_order == 6,
            },
        },
        "brown_vs_wilmot": {
            "Brown_1967": "Aut(S) = G_2 x S_3 with explicit (sigma, Psi) generators",
            "Wilmot_2025_arXiv_2512_07210": "Aut(S) = G_2 only; S_3 fails canonical 3-form preservation",
            "empirical_settlement_2026_05_17": verdict,
        },
    }
    out_path = ROOT / "queue_09_SS3TG_results.json"
    out_path.write_text(json.dumps(out, indent=2, ensure_ascii=False, default=lambda o: int(o) if hasattr(o, "item") else str(o)) + "\n")
    print(f"\nResults -> {out_path.name}")
    return out


if __name__ == "__main__":
    main()
