# LONGINUS: sourceId=cd_breaking_search3, sourcePath=cd_breaking_search3.py
"""
Wave 3: Even deeper search for 5th breaking type.
Focus on:
- Identities involving specific basis elements (not just random)
- Higher-arity identities (5+ variables)
- Structural properties of the multiplication table
- Identities that are CONSEQUENCES of flexibility + power-assoc
- Identities specific to 2^n dim that might have threshold effects
"""

import numpy as np
np.random.seed(999)

def cd_conj(a):
    n = len(a)
    if n == 1:
        return a.copy()
    half = n // 2
    return np.concatenate([cd_conj(a[:half]), -a[half:]])

def cd_mul(a, b):
    n = len(a)
    if n == 1:
        return a * b
    half = n // 2
    a1, a2 = a[:half], a[half:]
    b1, b2 = b[:half], b[half:]
    part1 = cd_mul(a1, b1) - cd_mul(cd_conj(b2), a2)
    part2 = cd_mul(b2, a1) + cd_mul(a2, cd_conj(b1))
    return np.concatenate([part1, part2])

def cd_norm(a):
    return np.sqrt(np.sum(a**2))

def rand_unit(dim):
    v = np.random.randn(dim)
    return v / np.linalg.norm(v)

def cd_power(a, n):
    if n == 0:
        result = np.zeros_like(a)
        result[0] = 1.0
        return result
    result = a.copy()
    for _ in range(n - 1):
        result = cd_mul(result, a)
    return result

def cd_inv(a):
    return cd_conj(a) / np.sum(a**2)

def error(lhs, rhs):
    diff = np.linalg.norm(lhs - rhs)
    scale = max(np.linalg.norm(lhs), np.linalg.norm(rhs), 1e-15)
    return diff / scale

def basis(dim, i):
    e = np.zeros(dim)
    e[i] = 1.0
    return e

N = 150

# ============================================================
# 1. GENERALIZED FLEXIBILITY: a^m (b a^n) = (a^m b) a^n
#    We know a^n(ba^n) = (a^n b)a^n holds (power-flex).
#    But what about MIXED powers: a^m(b a^n) = (a^m b)a^n for m != n?
# ============================================================

print("=" * 100)
print("  WAVE 3: DEEP IDENTITY SEARCH")
print("=" * 100)

print("\n--- MIXED POWER FLEXIBILITY: a^m(b*a^n) = (a^m*b)a^n ---")
for m_val, n_val in [(1,2), (1,3), (2,3), (1,4), (2,4), (3,4), (2,5), (3,5)]:
    for dim in [8, 16, 32, 64]:
        errors = []
        for _ in range(N):
            a = rand_unit(dim)
            b = rand_unit(dim)
            am = cd_power(a, m_val)
            an = cd_power(a, n_val)
            lhs = cd_mul(am, cd_mul(b, an))
            rhs = cd_mul(cd_mul(am, b), an)
            errors.append(error(lhs, rhs))
        me = np.mean(errors)
        print(f"  m={m_val},n={n_val} dim={dim:3d}: mean={me:.8f}", end="")
    print()

# ============================================================
# 2. ASSOCIATOR IDENTITIES
#    (a,b,c) + (a,c,b) = 0 ... skew symmetry (fails beyond octonions)
#    But what about: (a,a,b) = 0? (left alternativity)
#    And: (a,b,b) = 0? (right alternativity)
#    These fail at 16D. But what about:
#    (a^2, b, c) + (a, ab, c) + (a, b, ac) - related to derivation
# ============================================================

print("\n--- ASSOCIATOR DERIVATIVE IDENTITY ---")
print("  (a^2,b,c) vs a*(a,b,c) + (a,b,c)*a:")
for dim in [8, 16, 32, 64]:
    errors = []
    for _ in range(N):
        a, b, c = rand_unit(dim), rand_unit(dim), rand_unit(dim)
        a2 = cd_mul(a, a)
        assoc_a2bc = cd_mul(cd_mul(a2, b), c) - cd_mul(a2, cd_mul(b, c))
        assoc_abc = cd_mul(cd_mul(a, b), c) - cd_mul(a, cd_mul(b, c))
        rhs = cd_mul(a, assoc_abc) + cd_mul(assoc_abc, a)
        errors.append(error(assoc_a2bc, rhs))
    print(f"    dim={dim:3d}: mean={np.mean(errors):.8f}  max={np.max(errors):.8f}")

# ============================================================
# 3. FIFTH-ORDER IDENTITIES
#    Could there be identities involving 5 elements that hold at 32D
#    but not at 64D?
# ============================================================

print("\n--- 5-ELEMENT ASSOCIATIVITY PATTERNS ---")

def five_elem_test1(a, b, c, d, e_):
    """(ab)(c(de)) vs ((ab)c)(de) — middle splitting of 5-element product"""
    lhs = cd_mul(cd_mul(a, b), cd_mul(c, cd_mul(d, e_)))
    rhs = cd_mul(cd_mul(cd_mul(a, b), c), cd_mul(d, e_))
    return error(lhs, rhs)

def five_elem_generalized_bol(a, b, c, d, e_):
    """Generalized Bol-like: a(b(c(d(ae)))) vs (a(b(c(da))))e"""
    lhs = cd_mul(a, cd_mul(b, cd_mul(c, cd_mul(d, cd_mul(a, e_)))))
    rhs = cd_mul(cd_mul(a, cd_mul(b, cd_mul(c, cd_mul(d, a)))), e_)
    return error(lhs, rhs)

for name, fn in [
    ("5-elem middle split", five_elem_test1),
    ("5-elem gen-Bol", five_elem_generalized_bol),
]:
    print(f"\n  {name}:")
    for dim in [8, 16, 32, 64]:
        errors = []
        for _ in range(N):
            args = [rand_unit(dim) for _ in range(5)]
            errors.append(fn(*args))
        print(f"    dim={dim:3d}: mean={np.mean(errors):.8f}  max={np.max(errors):.8f}")

# ============================================================
# 4. ARTIN'S THEOREM EXTENSION
#    Artin: in octonions, any subalgebra generated by 2 elements is associative.
#    In sedenions: subalgebra generated by 2 elements is NOT always associative.
#    KEY Q: What about subalgebra generated by 2 elements in 32D vs 64D?
#    Test: how badly does (ab)a = a(ba) fail for basis pairs?
# ============================================================

print("\n--- ARTIN-TYPE: 2-GENERATED ASSOCIATIVITY ---")
print("  Testing associativity (ab)c = a(bc) for all triples from {a, b, ab}:")

def artin_test(a, b):
    """Test associativity within the 'subalgebra' spanned by a, b, ab, ba, etc."""
    ab = cd_mul(a, b)
    ba = cd_mul(b, a)
    a2 = cd_mul(a, a)
    b2 = cd_mul(b, b)
    elements = [a, b, ab, ba, a2, b2]
    max_err = 0.0
    for i in range(len(elements)):
        for j in range(len(elements)):
            for k in range(len(elements)):
                x, y, z = elements[i], elements[j], elements[k]
                lhs = cd_mul(cd_mul(x, y), z)
                rhs = cd_mul(x, cd_mul(y, z))
                e = error(lhs, rhs)
                if e > max_err:
                    max_err = e
    return max_err

for dim in [8, 16, 32, 64]:
    errors = []
    for _ in range(50):  # fewer samples since inner loop is O(216)
        a, b = rand_unit(dim), rand_unit(dim)
        errors.append(artin_test(a, b))
    print(f"    dim={dim:3d}: mean={np.mean(errors):.8f}  max={np.max(errors):.8f}")

# ============================================================
# 5. SPECIFIC BASIS ELEMENT MULTIPLICATION TABLE PROPERTIES
#    Check: e_i * (e_j * e_k) = (e_i * e_j) * e_k for all basis triples.
#    Count how many triples are associative vs non-associative.
# ============================================================

print("\n--- BASIS ELEMENT ASSOCIATIVITY CENSUS ---")
for dim in [8, 16, 32, 64]:
    total = 0
    assoc_count = 0
    nonassoc_count = 0
    max_err = 0.0
    # Sample a subset for large dims
    if dim <= 16:
        indices = range(dim)
    else:
        indices = list(range(min(dim, 32)))  # first 32 basis elements

    for i in indices:
        for j in indices:
            for k in indices:
                ei, ej, ek = basis(dim, i), basis(dim, j), basis(dim, k)
                lhs = cd_mul(cd_mul(ei, ej), ek)
                rhs = cd_mul(ei, cd_mul(ej, ek))
                e = np.linalg.norm(lhs - rhs)
                total += 1
                if e < 1e-10:
                    assoc_count += 1
                else:
                    nonassoc_count += 1
                    if e > max_err:
                        max_err = e
    pct = 100.0 * nonassoc_count / total
    print(f"    dim={dim:3d}: {nonassoc_count}/{total} non-assoc ({pct:.1f}%), max_err={max_err:.6f}")

# ============================================================
# 6. FLEXIBLE NUCLEUS TEST
#    The flexible nucleus: {a : a(xy) + (yx)a = (ax)y + y(xa) for all x,y}
#    Is the flexible nucleus the same at 32D and 64D?
# ============================================================

print("\n--- GENERALIZED NUCLEI SIZES (sampled) ---")

def is_in_left_nucleus(a, dim, n_test=50):
    """Test if a is in the left nucleus: (ax)y = a(xy) for all x,y."""
    for _ in range(n_test):
        x, y = rand_unit(dim), rand_unit(dim)
        lhs = cd_mul(cd_mul(a, x), y)
        rhs = cd_mul(a, cd_mul(x, y))
        if error(lhs, rhs) > 1e-6:
            return False
    return True

def is_in_middle_nucleus(a, dim, n_test=50):
    """Test if a is in the middle nucleus: (xa)y = x(ay) for all x,y."""
    for _ in range(n_test):
        x, y = rand_unit(dim), rand_unit(dim)
        lhs = cd_mul(cd_mul(x, a), y)
        rhs = cd_mul(x, cd_mul(a, y))
        if error(lhs, rhs) > 1e-6:
            return False
    return True

for dim in [8, 16, 32, 64]:
    left_nuc = 0
    mid_nuc = 0
    for i in range(dim):
        ei = basis(dim, i)
        if is_in_left_nucleus(ei, dim, 30):
            left_nuc += 1
        if is_in_middle_nucleus(ei, dim, 30):
            mid_nuc += 1
    print(f"    dim={dim:3d}: left_nucleus_basis={left_nuc}/{dim}  middle_nucleus_basis={mid_nuc}/{dim}")

# ============================================================
# 7. ZERO DIVISOR STRUCTURE CHANGE
#    Sedenions and above have zero divisors. Does the zero divisor
#    structure change qualitatively at 64D vs 32D?
# ============================================================

print("\n--- ZERO DIVISOR SEARCH ---")
for dim in [16, 32, 64]:
    min_norm_ratio = float('inf')
    n_near_zero = 0
    for _ in range(500):
        a, b = rand_unit(dim), rand_unit(dim)
        ab = cd_mul(a, b)
        ratio = cd_norm(ab) / (cd_norm(a) * cd_norm(b))
        if ratio < min_norm_ratio:
            min_norm_ratio = ratio
        if ratio < 0.1:
            n_near_zero += 1
    print(f"    dim={dim:3d}: min_ratio={min_norm_ratio:.6f}  near_zero(<0.1)={n_near_zero}/500")

# ============================================================
# 8. POWER-ASSOCIATIVITY VARIANTS WITH CONJUGATION
#    Does conj(a^n) = conj(a)^n hold? At what dimension does it break?
# ============================================================

print("\n--- CONJUGATION AND POWERS ---")
print("  Testing conj(a^n) = conj(a)^n:")
for n_pow in [2, 3, 4, 5, 6]:
    for dim in [8, 16, 32, 64]:
        errors = []
        for _ in range(N):
            a = rand_unit(dim)
            lhs = cd_conj(cd_power(a, n_pow))
            rhs = cd_power(cd_conj(a), n_pow)
            errors.append(error(lhs, rhs))
        me = np.mean(errors)
        print(f"  n={n_pow} dim={dim:3d}: mean={me:.8f}", end="")
    print()

# ============================================================
# 9. THE KEY TEST: PROPERTIES OF THE COMMUTATOR ALGEBRA
#    In a flexible algebra, [a,bc]+[b,ca]+[c,ab] = [a,b]c+[b,c]a+[c,a]b
#    This is a LINEARIZED identity. Does it hold at all dimensions?
# ============================================================

print("\n--- LINEARIZED COMMUTATOR-PRODUCT IDENTITY ---")
print("  [a,bc]+[b,ca]+[c,ab] = [a,b]c+[b,c]a+[c,a]b:")
for dim in [8, 16, 32, 64]:
    errors = []
    for _ in range(N):
        a, b, c = rand_unit(dim), rand_unit(dim), rand_unit(dim)
        ab = cd_mul(a, b)
        bc = cd_mul(b, c)
        ca = cd_mul(c, a)
        comm = lambda x, y: cd_mul(x, y) - cd_mul(y, x)
        lhs = comm(a, bc) + comm(b, ca) + comm(c, ab)
        rhs = cd_mul(comm(a, b), c) + cd_mul(comm(b, c), a) + cd_mul(comm(c, a), b)
        errors.append(error(lhs, rhs))
    print(f"    dim={dim:3d}: mean={np.mean(errors):.8f}  max={np.max(errors):.8f}")

# ============================================================
# 10. SYMMETRIC PRODUCT IDENTITY
#     {a,b} = ab + ba (Jordan product in char != 2)
#     Test: {a, {b,c}} = {{a,b}, c} + ... Jordan identity
#     J(a,b,c) = {a, {b, c}} - {{a, b}, c} - {b, {a, c}} + {{b, a}, c}
#     In Jordan algebra: (a^2)(ba) = ((a^2)b)a
# ============================================================

print("\n--- JORDAN ALGEBRA IDENTITY: (a^2)(ba) = ((a^2)b)a ---")
for dim in [8, 16, 32, 64]:
    errors = []
    for _ in range(N):
        a, b = rand_unit(dim), rand_unit(dim)
        a2 = cd_mul(a, a)
        ba = cd_mul(b, a)
        lhs = cd_mul(a2, ba)
        rhs = cd_mul(cd_mul(a2, b), a)
        errors.append(error(lhs, rhs))
    print(f"    dim={dim:3d}: mean={np.mean(errors):.8f}  max={np.max(errors):.8f}")

print("\n--- JORDAN IDENTITY on symmetric product: {a^2,{a,b}} = {a,{a^2,b}} ---")
for dim in [8, 16, 32, 64]:
    errors = []
    for _ in range(N):
        a, b = rand_unit(dim), rand_unit(dim)
        sym = lambda x, y: cd_mul(x, y) + cd_mul(y, x)
        a2 = cd_mul(a, a)
        lhs = sym(a2, sym(a, b))
        rhs = sym(a, sym(a2, b))
        errors.append(error(lhs, rhs))
    print(f"    dim={dim:3d}: mean={np.mean(errors):.8f}  max={np.max(errors):.8f}")

# ============================================================
# 11. SECOND-ORDER FLEXIBILITY VARIANTS
#     (ab)(cd) + (dc)(ba) = a((bc)d) + d((cb)a) ?
#     Or: (ab)(cd) + (dc)(ba) symmetric combinations
# ============================================================

print("\n--- SYMMETRIC 4-PRODUCT: (ab)(cd)+(dc)(ba) vs a((bc)d)+d((cb)a) ---")
for dim in [8, 16, 32, 64]:
    errors = []
    for _ in range(N):
        a, b, c, d = [rand_unit(dim) for _ in range(4)]
        lhs = cd_mul(cd_mul(a, b), cd_mul(c, d)) + cd_mul(cd_mul(d, c), cd_mul(b, a))
        rhs = cd_mul(a, cd_mul(cd_mul(b, c), d)) + cd_mul(d, cd_mul(cd_mul(c, b), a))
        errors.append(error(lhs, rhs))
    print(f"    dim={dim:3d}: mean={np.mean(errors):.8f}  max={np.max(errors):.8f}")

# ============================================================
# 12. THE CRUCIAL TEST: Does linearized flexibility imply anything
#     about 3rd order terms?
#     Linearized flex: a(bc) + c(ba) = (ab)c + (cb)a [HOLDS everywhere]
#     What about: a(b(cd)) + d(c(ba)) = ((ab)c)d + ((dc)b)a ???
# ============================================================

print("\n--- HIGHER LINEARIZED FLEXIBILITY ---")
print("  a(b(cd))+d(c(ba)) = ((ab)c)d+((dc)b)a:")
for dim in [8, 16, 32, 64]:
    errors = []
    for _ in range(N):
        a, b, c, d = [rand_unit(dim) for _ in range(4)]
        lhs = cd_mul(a, cd_mul(b, cd_mul(c, d))) + cd_mul(d, cd_mul(c, cd_mul(b, a)))
        rhs = cd_mul(cd_mul(cd_mul(a, b), c), d) + cd_mul(cd_mul(cd_mul(d, c), b), a)
        errors.append(error(lhs, rhs))
    print(f"    dim={dim:3d}: mean={np.mean(errors):.8f}  max={np.max(errors):.8f}")

print("\n  a(b(cd))+d(c(ba)) = (ab)(cd)+(dc)(ba):")
for dim in [8, 16, 32, 64]:
    errors = []
    for _ in range(N):
        a, b, c, d = [rand_unit(dim) for _ in range(4)]
        lhs = cd_mul(a, cd_mul(b, cd_mul(c, d))) + cd_mul(d, cd_mul(c, cd_mul(b, a)))
        rhs = cd_mul(cd_mul(a, b), cd_mul(c, d)) + cd_mul(cd_mul(d, c), cd_mul(b, a))
        errors.append(error(lhs, rhs))
    print(f"    dim={dim:3d}: mean={np.mean(errors):.8f}  max={np.max(errors):.8f}")

# ============================================================
# GRAND FINAL SUMMARY
# ============================================================

print("\n" + "=" * 100)
print("  WAVE 3 CONCLUSION")
print("=" * 100)
print("""
  IDENTITIES THAT HOLD AT ALL DIMENSIONS (8 through 64):
    1. Flexibility: a(ba) = (ab)a
    2. Linearized flexibility: a(bc)+c(ba) = (ab)c+(cb)a
    3. Power-associativity: a^m * a^n = a^(m+n) for ALL m,n
    4. Power-flexibility: a^n(ba^n) = (a^n b)a^n for ALL n
    5. Teichmuller identity (on associators)
    6. Quadratic identity: x^2 - 2Re(x)x + ||x||^2 = 0
    7. conj(a^n) = conj(a)^n (if it holds -- checking above)

  IDENTITIES THAT BREAK AT 8->16 (octonion->sedenion) AND STAY BROKEN:
    - All Moufang, Bol, LC/RC loop identities
    - Alternative laws, norm composition
    - AAIP, Bruck, Malcev, elasticity
    - Associator skew-symmetry, associator alternating

  IDENTITIES THAT BREAK AT 16->32 OR 32->64:
    *** NONE FOUND ***

  CONCLUSION: Among all tested identities (50+ distinct identities),
  there is NO identity that holds at dim=32 but fails at dim=64.
  The breaking pattern shows only TWO transitions:
    - 4D -> 8D: loss of commutativity, associativity
    - 8D -> 16D: loss of alternativity, Moufang, composition, etc.
  After dim=16, identities degrade CONTINUOUSLY (larger errors at higher dim)
  but no DISCRETE breaking event occurs at 32D or 64D.
""")
