export const excludedTopLevelKeys = new Set([
  "verdict",
  "verdict_reasoning",
  "verdict_source",
  "verdict_date",
  "self_refutation",
  "sub_verdicts",
  "verdict_provenance",
  "verdict_reasoning_prior",
  "mc_evidence_ref",
  "mc_null_model",
  "mc_p_e_given_not_h",
  "mc_verdict_reasoning",
  "mc_layer1_rel_diff_literal_pct",
  "mc_layer1_rel_diff_reciprocal_pct",
  "mc_null_model_layer3",
  "mc_p_e_given_not_h_layer3",
  "researchedAt",
  "timestamp",
  "generated_at",
  "createdAt",
  "run_at"
])

export interface DefaultNumericRule {
  readonly kind: "close"
  readonly relativeTolerance: number
  readonly absoluteTolerance: number
}

export type PathNumericRule =
  | {
      readonly path: string
      readonly kind: "close"
      readonly relativeTolerance: number
      readonly absoluteTolerance: number
    }
  | {
      readonly path: string
      readonly kind: "circular"
      readonly period: number
      readonly absoluteTolerance: number
    }
  | {
      readonly path: string
      readonly kind: "near-zero"
      readonly absoluteTolerance: number
    }

export interface ComparePolicy {
  readonly defaultNumeric: DefaultNumericRule
  readonly pathRules?: ReadonlyArray<PathNumericRule>
}

export type ReproCase =
  | {
      readonly name: string
      readonly script: string
      readonly output: string
      readonly policy: "portable"
      readonly compare: ComparePolicy
    }
  | {
      readonly name: string
      readonly script: string
      readonly output: string
      readonly policy: "nonportable"
      readonly reason: string
    }
  | {
      readonly name: string
      readonly script: string
      readonly output: string
      readonly policy: "superseded"
      readonly reason: string
    }

const tight: ComparePolicy = {
  defaultNumeric: {
    kind: "close",
    relativeTolerance: 1e-12,
    absoluteTolerance: 1e-15
  }
}

export const reproCases = [
  {
    name: "derive_Lstar_from_ICE",
    script: "derive_Lstar_from_ICE.py",
    output: "derive_Lstar_results.json",
    policy: "portable",
    compare: tight
  },
  {
    name: "derive_dimensionless_ICE",
    script: "derive_dimensionless_ICE.py",
    output: "derive_dimensionless_results.json",
    policy: "portable",
    compare: tight
  },
  {
    name: "derive_mass_ratios_ICE",
    script: "derive_mass_ratios_ICE.py",
    output: "derive_mass_ratios_results.json",
    policy: "portable",
    compare: tight
  },
  {
    name: "prove_higgs_ZD_doublet",
    script: "prove_higgs_ZD_doublet.py",
    output: "prove_higgs_results.json",
    policy: "portable",
    compare: tight
  },
  {
    name: "prove_s3_higher_gauge",
    script: "prove_s3_higher_gauge.py",
    output: "prove_s3_results.json",
    policy: "portable",
    compare: tight
  },
  {
    name: "prove_s5_bv_ainfty",
    script: "prove_s5_bv_ainfty.py",
    output: "prove_s5_results.json",
    policy: "portable",
    compare: {
      ...tight,
      pathRules: [
        {
          path: "$.S5.4.s5_4_master_residual",
          kind: "near-zero",
          absoluteTolerance: 1e-12
        }
      ]
    }
  },
  {
    name: "queue_01_orbit_analysis",
    script: "queue_01_orbit_analysis.py",
    output: "queue_01_orbit_results.json",
    policy: "portable",
    compare: tight
  },
  {
    name: "queue_03_threshold_sensitivity_scan",
    script: "queue_03_threshold_sensitivity_scan.py",
    output: "queue_03_threshold_sensitivity_results.json",
    policy: "nonportable",
    reason:
      "legacy metric max(abs(commutator)) depends on scipy null_space's arbitrary orthogonal basis; a tolerance cannot repair changed pass/fail counts"
  },
  {
    name: "queue_04_hosotani_toy",
    script: "queue_04_hosotani_toy.py",
    output: "queue_04_hosotani_results.json",
    policy: "portable",
    compare: {
      ...tight,
      pathRules: [
        {
          path: "$.case3_realistic.best_theta[*]",
          kind: "circular",
          period: 2 * Math.PI,
          absoluteTolerance: 1e-6
        },
        {
          path: "$.case3_realistic.theta_spread",
          kind: "close",
          relativeTolerance: 0,
          absoluteTolerance: 1e-6
        }
      ]
    }
  },
  {
    name: "queue_05_coleman_weinberg",
    script: "queue_05_coleman_weinberg.py",
    output: "queue_05_cw_results.json",
    policy: "portable",
    compare: tight
  },
  {
    name: "queue_06_cooperative_vacuum",
    script: "queue_06_cooperative_vacuum.py",
    output: "queue_06_coop_results.json",
    policy: "superseded",
    reason:
      "committed output is generated by inconclusive_redo.py (method_fix and larger n_trials), not by the mapped historical script"
  },
  {
    name: "queue_10_group_of_6",
    script: "queue_10_group_of_6.py",
    output: "queue_10_group6_results.json",
    policy: "portable",
    compare: tight
  },
  {
    name: "queue_11_xor_invariant",
    script: "queue_11_xor_invariant.py",
    output: "queue_11_xor_results.json",
    policy: "portable",
    compare: tight
  },
  {
    name: "verify_mp_mW_3_256",
    script: "verify_mp_mW_3_256.py",
    output: "verify_mp_mW_results.json",
    policy: "portable",
    compare: tight
  }
] as const satisfies ReadonlyArray<ReproCase>

export const outputForScript = (name: string): string | undefined =>
  reproCases.find((entry) => entry.name === name)?.output
