#!/usr/bin/env python3
"""Gate 1 -- selected-H support-restricted spectral intertwiner.

This bounded non-numbered calculation uses the already selected p-positive
Fourier--Kontorovich--Lebedev spectral representation of the densitized
constraint.  It constructs an exact coordinate unitary only to the proper
target ``c < 3 p**2`` and gives a joint-spectral obstruction to a
p-preserving exact unitary into the previously declared unrestricted M_c
representation.  Its delta kernel is a compact-interior *spectral* graph
kernel in (kappa,p) and (c,p); it is not the old endpoint FIO generated by
W(c,P,p), and does not repair that one-term kernel's nonunitarity.
"""

from __future__ import annotations

import hashlib
import json
import platform
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import sympy as sp


INPUT_NAME = "GATE1_V0_ENDPOINT_SUPPORT_RESTRICTED_SPECTRAL_INTERTWINER_INPUTS.json"
RESULT_NAME = "GATE1_V0_ENDPOINT_SUPPORT_RESTRICTED_SPECTRAL_INTERTWINER_RESULT.json"
INPUT_RELPATH = f"cpt_temporal_folded_susy/{INPUT_NAME}"
RUNNER_RELPATH = (
    "cpt_temporal_folded_susy/"
    "gate1_v0_endpoint_support_restricted_spectral_intertwiner.py"
)
EXPECTED_INPUT_SHA256 = (
    "2ead98d6fb7aa502891b8399b278a3fd1a898c15985606b82a02502c6d05fde0"
)
CALCULATION_ID = "Gate1V0EndpointSupportRestrictedSpectralIntertwiner"
RESULT_SCHEMA = "ice.gate1.v0-endpoint-support-restricted-spectral-intertwiner.result.v1"
RESULT_PREFIX = "GATE1_V0_ENDPOINT_SUPPORT_RESTRICTED_SPECTRAL_INTERTWINER_RESULT="
ARTIFACT_CAP_BYTES = 1_000_000


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def canonical_bytes(value: object) -> bytes:
    return json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        allow_nan=False,
    ).encode("utf-8")


@dataclass
class Audit:
    exact: list[dict[str, Any]] = field(default_factory=list)
    theorem_guards: list[dict[str, Any]] = field(default_factory=list)
    seen_ids: set[str] = field(default_factory=set, repr=False)

    def register(self, check_id: str) -> None:
        if check_id in self.seen_ids:
            raise AssertionError(f"duplicate audit id: {check_id}")
        self.seen_ids.add(check_id)

    def observe(self, check_id: str, passed: bool, statement: str) -> bool:
        self.register(check_id)
        observed = bool(passed)
        self.exact.append(
            {"id": check_id, "passed": observed, "statement": statement}
        )
        return observed

    def guard(
        self,
        guard_id: str,
        theorem: str,
        hypotheses: str,
        conclusion_and_scope: str,
    ) -> None:
        self.register(guard_id)
        self.theorem_guards.append(
            {
                "id": guard_id,
                "verified": True,
                "verification_mode": "ANALYTIC_HYPOTHESIS_AND_SCOPE_AUDIT",
                "theorem": theorem,
                "hypotheses": hypotheses,
                "conclusion_and_scope": conclusion_and_scope,
            }
        )


def verify_upstream(root: Path, item: dict[str, Any]) -> dict[str, str]:
    path = root / item["path"]
    raw = path.read_bytes()
    observed = sha256_bytes(raw)
    if observed != item["sha256"]:
        raise AssertionError(
            f"upstream hash mismatch for {item['path']}: {observed}"
        )
    payload = json.loads(raw)
    if payload.get("run_status") != "VALID_RUN":
        raise AssertionError(f"upstream not valid: {item['path']}")
    if payload.get("verdict") != item["required_verdict"]:
        raise AssertionError(f"upstream verdict mutation: {item['path']}")
    if (
        payload.get("result_payload_sha256_without_self")
        != item["payload_sha256_without_self"]
    ):
        raise AssertionError(f"upstream payload mutation: {item['path']}")
    return {
        "path": item["path"],
        "sha256": observed,
        "payload_sha256_without_self": payload[
            "result_payload_sha256_without_self"
        ],
        "verdict": payload["verdict"],
    }


def expected_nulls() -> dict[str, Any]:
    return {
        "raw_C_operator_equivalence": None,
        "raw_C_rigging_map": None,
        "raw_C_physical_inner_product": None,
        "selected_raw_C_extension": None,
        "exact_endpoint_state_transform": None,
        "W_full_symbol": None,
        "old_endpoint_FIO_exact_unitarity_repaired": None,
        "global_kappa_zero_or_c_boundary_completion": None,
        "cross_branch_gluing_or_origin_atom": None,
        "declared_unrestricted_Mc_intertwiner": None,
        "absolute_bfv_measure": None,
        "quantum_bfv_anomaly_freedom": None,
        "relational_observables_or_decoherence": None,
        "empirical_likelihood": None,
        "physical_original_cycle": None,
        "global_n_sigma": None,
        "quantum_gravity_claim": None,
        "physics_claim": None,
        "TOE_claim": None,
        "global_promotion": "PROHIBITED",
        "gate1": "OPEN_PARTIAL_PROGRESS",
        "automatic_next": None,
    }


def load_input() -> tuple[dict[str, Any], str, list[dict[str, str]]]:
    if len(sys.argv) != 1:
        raise AssertionError("this bounded calculation accepts no arguments")
    path = Path(__file__).with_name(INPUT_NAME)
    raw = path.read_bytes()
    observed = sha256_bytes(raw)
    if observed != EXPECTED_INPUT_SHA256:
        raise AssertionError(
            f"input hash mismatch: expected {EXPECTED_INPUT_SHA256}, "
            f"observed {observed}"
        )
    payload = json.loads(raw)
    if payload["schema_version"] != (
        "ice.gate1.v0-endpoint-support-restricted-spectral-intertwiner.input.v1"
    ):
        raise AssertionError("unexpected input schema")
    if payload["calculation_id"] != CALCULATION_ID:
        raise AssertionError("unexpected calculation identity")
    if payload["numbered_phase"] is not None:
        raise AssertionError("numbered phase mutation")
    expected_caps = {
        "wall_clock_seconds": 120,
        "stdout_bytes": 262144,
        "stderr_bytes": 262144,
        "changed_artifact_files": 12,
        "changed_artifact_bytes": 1000000,
        "root_calls": 0,
        "quadratures": 0,
        "ode_calls": 0,
        "automatic_descendants": 0,
    }
    if payload["resource_caps"] != expected_caps:
        raise AssertionError("resource cap mutation")
    if payload["required_fail_closed_outputs"] != expected_nulls():
        raise AssertionError("fail-closed output mutation")
    model = payload["declared_model"]
    if (
        "c<3*p^2" not in model["restricted_target"]
        or "not the W(c,P,p) endpoint FIO" not in model["old_fio_boundary"]
        or model["component_boundary"]
        != "p>0 throughout; this does not import the full-p completion or create a p=0 atom"
    ):
        raise AssertionError("declared spectral-target scope mutation")
    root = Path(__file__).resolve().parent.parent
    upstream = [verify_upstream(root, item) for item in payload["upstream_results"]]
    return payload, observed, upstream


def exact_calculation(audit: Audit) -> tuple[dict[str, Any], dict[str, bool]]:
    c, kappa, p, hbar = sp.symbols(
        "c kappa p hbar", positive=True, real=True
    )
    c_general = sp.symbols("c_general", real=True)
    h = 3 * p**2 - 2 * hbar**2 * kappa**2
    kappa_of_c = sp.sqrt((3 * p**2 - c_general) / (2 * hbar**2))
    jacobian = 4 * hbar**2 * kappa
    jacobian_of_c = sp.simplify(jacobian.subs(kappa, kappa_of_c))
    flags: dict[str, bool] = {}

    flags["coordinate_inverse"] = audit.observe(
        "G1.endpoint.spectral.coordinate_inverse_and_jacobian",
        sp.simplify(h.subs(kappa, kappa_of_c) - c_general) == 0
        and sp.simplify(sp.diff(h, kappa) + jacobian) == 0
        and jacobian.is_positive is True,
        "on Y_plus, kappa(c,p)=sqrt((3p^2-c)/(2hbar^2)) inverts c=h(kappa,p), and J=|partial_kappa h|=4hbar^2*kappa is strictly positive",
    )

    test_amplitude = sp.Function("A")(kappa, p)
    coarea_integrand = sp.sqrt(jacobian) * test_amplitude / jacobian
    flags["kernel_coarea"] = audit.observe(
        "G1.endpoint.spectral.delta_kernel_coarea_normalization",
        sp.simplify(coarea_integrand - test_amplitude / sp.sqrt(jacobian)) == 0,
        "the distributional kernel sqrt(J)*delta(c-h(kappa,p)) gives the declared J^(-1/2) pullback after the one-dimensional coarea factor",
    )

    flags["unitary_change_of_variables"] = audit.observe(
        "G1.endpoint.spectral.unitary_change_of_variables",
        sp.simplify(jacobian * (1 / sp.sqrt(jacobian)) ** 2 - 1) == 0
        and sp.simplify((1 / sp.sqrt(jacobian_of_c)) ** 2 * jacobian_of_c - 1)
        == 0,
        "dc=J d kappa and the J^(-1/2) factor make V an isometry from L2(dkappa dp) to L2(dc dp) on the proper support-restricted target",
    )

    flags["operator_intertwining"] = audit.observe(
        "G1.endpoint.spectral.operator_and_domain_intertwining",
        sp.simplify(h.subs(kappa, kappa_of_c) - c_general) == 0
        and sp.simplify(p - p) == 0,
        "V M_h V^(-1)=M_c_less and V p V^(-1)=p; the same change-of-variables identity transports their maximal multiplication domains",
    )

    kappa_zero = sp.sqrt(sp.Rational(3, 2)) * p / hbar
    jacobian_zero = sp.simplify(jacobian.subs(kappa, kappa_zero))
    expected_zero_jacobian = 2 * sp.sqrt(6) * hbar * p
    flags["zero_fiber"] = audit.observe(
        "G1.endpoint.spectral.zero_fiber_measure_pullback",
        sp.simplify(jacobian_zero - expected_zero_jacobian) == 0
        and sp.simplify(
            1 / jacobian_zero - 1 / expected_zero_jacobian
        )
        == 0,
        "because c=0 lies in Y_plus for p>0, the target dc delta-fiber form pulls back through V to dp/(2sqrt(6)hbar p), exactly the selected H RAQ shell weight",
    )

    p_w = sp.symbols("p_w", positive=True, real=True)
    c_w = sp.symbols("c_w", positive=True, real=True)
    witness_norm_squared = sp.integrate(
        sp.integrate(sp.Integer(1), (c_w, 4 * p_w**2, 5 * p_w**2)),
        (p_w, 1, 2),
    )
    flags["unrestricted_complement_witness"] = audit.observe(
        "G1.endpoint.spectral.unrestricted_target_positive_measure_witness",
        sp.simplify(witness_norm_squared - sp.Rational(7, 3)) == 0
        and witness_norm_squared.is_positive is True,
        "the explicit target witness 1_{1<p<2,4p^2<c<5p^2} has positive squared L2 norm 7/3 and lies in E={c>=3p^2,p>0}",
    )

    flags["joint_support_obstruction"] = audit.observe(
        "G1.endpoint.spectral.p_preserving_unrestricted_joint_support_obstruction",
        sp.simplify(3 * p**2 - h - 2 * hbar**2 * kappa**2) == 0
        and (3 * p**2 - h).is_positive is True,
        "on every source point kappa>0, h(kappa,p)<3p^2, so the E joint spectral projection vanishes on the source while the previous positive-measure witness has nonzero unrestricted-target E projection",
    )

    audit.guard(
        "G1.endpoint.spectral.guard.maximal_multiplication_and_unitary_conjugation",
        "maximal real multiplication-operator theorem and unitary conjugation",
        "h and c are real measurable multipliers on their stated sigma-finite measures; the coordinate map is a smooth bijection between open X_plus and Y_plus with J>0",
        "V is an exact selected-H spectral-coordinate unitary and transports the maximal domains of M_h, M_c_less and p only; it supplies no raw-C operator or physical endpoint state.",
    )
    audit.guard(
        "G1.endpoint.spectral.guard.coarea_zero_fiber",
        "one-dimensional change of variables and distributional spectral-fiber evaluation",
        "all test amplitudes are smooth and compactly supported strictly inside p>0 and kappa>0 before applying the delta form",
        "the c=0 pullback reproduces the selected H RAQ measure on that common test class; it is not a bounded delta projector or a general raw-C physical product.",
    )
    audit.guard(
        "G1.endpoint.spectral.guard.joint_spectral_obstruction",
        "joint spectral projections under a p-preserving unitary intertwiner",
        "an asserted U obeys U M_h U^-1=M_c and U p U^-1=p on the declared maximal domains, so its joint spectral projections must be carried to those of (M_c,p)",
        "the nonzero E target projection and zero source E projection rule out such a p-preserving exact unitary to the unrestricted declared M_c target. This does not rule out a unitary that abandons p preservation.",
    )
    audit.guard(
        "G1.endpoint.spectral.guard.compact_interior_fio_only",
        "local graph Fourier-integral-operator interpretation",
        "the delta kernel is restricted to compact subsets with kappa bounded away from zero, where the coordinate graph is smooth and J is nonzero",
        "it has a compact-interior spectral graph-FIO interpretation only; no global claim at kappa=0/c=3p^2, no Maslov gluing, and no identification with the old W endpoint FIO follows.",
    )
    audit.guard(
        "G1.endpoint.spectral.guard.old_endpoint_kill_retained",
        "scope separation from the frozen principal endpoint calculation",
        "the hash-verified upstream one-term W(c,P,p) kernel remains KILL for exact finite-hbar unitarity and the present source coordinates are kappa rather than P",
        "the spectral-coordinate unitary neither repairs the old one-term kernel nor selects its full symbol or an exact endpoint-state transform.",
    )

    return (
        {
            "source_spectral_space": "X_plus=(0,infinity)_kappa times (0,infinity)_p with L2(dkappa dp)",
            "restricted_target": "Y_plus={(c,p):p>0,c<3p^2} with L2(dc dp)",
            "coordinate_map": {
                "h": "3*p^2-2*hbar^2*kappa^2",
                "kappa_of_c": "sqrt((3*p^2-c)/(2*hbar^2))",
                "jacobian": "4*hbar^2*kappa",
                "jacobian_at_zero_fiber": "2*sqrt(6)*hbar*p",
            },
            "spectral_unitary": {
                "V": "(V A)(c,p)=J(c,p)^(-1/2)*A(kappa(c,p),p)",
                "V_inverse": "(V^(-1)F)(kappa,p)=sqrt(J(kappa,p))*F(h(kappa,p),p)",
                "kernel": "delta(p-p_prime)*sqrt(J(kappa,p))*delta(c-h(kappa,p))",
                "intertwines": ["M_h with M_c_less", "p with p"],
            },
            "unrestricted_target_obstruction": {
                "E": "{(c,p):p>0,c>=3*p^2}",
                "target_witness": "1_{1<p<2,4*p^2<c<5*p^2}",
                "target_witness_norm_squared": "7/3",
                "source_E_projection": "zero because h(kappa,p)<3*p^2 for kappa>0",
                "conclusion": "no exact unitary that simultaneously intertwines the selected H and p with the declared unrestricted (M_c,p)",
            },
            "scope_boundary": {
                "old_W_endpoint_FIO": None,
                "global_kappa_zero_boundary": None,
                "raw_C_equivalence": None,
            },
            "flags": flags,
        },
        flags,
    )


def write_result(path: Path, payload: dict[str, Any]) -> tuple[str, int]:
    payload["result_payload_sha256_without_self"] = sha256_bytes(
        canonical_bytes(payload)
    )
    encoded = canonical_bytes(payload)
    if len(encoded) > ARTIFACT_CAP_BYTES:
        raise AssertionError("result artifact byte cap exceeded")
    path.write_bytes(encoded)
    return sha256_bytes(encoded), len(encoded)


def main() -> None:
    input_payload, input_sha, upstream = load_input()
    audit = Audit()
    exact, flags = exact_calculation(audit)
    exact_pass = all(item["passed"] for item in audit.exact)
    if exact_pass:
        verdict = (
            "NARROW_V0_SELECTED_H_EXACT_SPECTRAL_INTERTWINER_REQUIRES_"
            "SUPPORT_RESTRICTED_TARGET"
        )
        impact = (
            "KEEP_EXACT_SELECTED_H_SPECTRAL_COORDINATE_MAP_KILL_P_PRESERVING_"
            "UNRESTRICTED_MC_INTERTWINER_KEEP_RAW_C_AND_W_ENDPOINT_DEBTS_OPEN"
        )
    else:
        verdict = "KILL_V0_SELECTED_H_SUPPORT_RESTRICTED_SPECTRAL_INTERTWINER"
        impact = (
            "RETAIN_PRIOR_SELECTED_H_AND_LOCAL_PRINCIPAL_FIO_RESULTS_WITHOUT_"
            "THIS_SPECTRAL_TARGET_CLAIM"
        )
    result: dict[str, Any] = {
        "schema_version": RESULT_SCHEMA,
        "calculation_id": CALCULATION_ID,
        "numbered_phase": None,
        "run_status": "VALID_RUN",
        "verdict": verdict,
        "programme_impact": impact,
        "input_manifest": {"path": INPUT_RELPATH, "sha256": input_sha},
        "upstream_results": upstream,
        "primary_sources": input_payload["primary_sources"],
        "declared_model": input_payload["declared_model"],
        "exact_calculation": exact,
        "exact_checks": audit.exact,
        "theorem_guards": audit.theorem_guards,
        "check_summary": {
            "exact_passed": sum(item["passed"] for item in audit.exact),
            "exact_total": len(audit.exact),
            "theorem_guard_count": len(audit.theorem_guards),
            "all_executable_checks_passed": exact_pass,
        },
        "computed_scope": input_payload["computed_scope"],
        "not_computed": input_payload["not_computed"],
        "required_fail_closed_outputs": expected_nulls(),
        "resource_accounting": {
            "root_calls": 0,
            "quadratures": 0,
            "ode_calls": 0,
            "adjacent_result_files_written": 1,
            "automatic_descendants": 0,
            "automatic_next": None,
        },
        "runner": {
            "path": RUNNER_RELPATH,
            "sha256": sha256_bytes(Path(__file__).read_bytes()),
        },
        "environment": {
            "python": platform.python_version(),
            "platform": platform.platform(),
            "sympy": sp.__version__,
        },
        "audit_flags": flags,
    }
    outer_sha, size = write_result(Path(__file__).with_name(RESULT_NAME), result)
    print(
        RESULT_PREFIX
        + json.dumps(
            {
                "run_status": result["run_status"],
                "verdict": verdict,
                "programme_impact": impact,
                "exact_passed": result["check_summary"]["exact_passed"],
                "exact_total": result["check_summary"]["exact_total"],
                "theorem_guard_count": result["check_summary"][
                    "theorem_guard_count"
                ],
                "result_sha256": outer_sha,
                "result_size_bytes": size,
                "automatic_next": None,
            },
            sort_keys=True,
            separators=(",", ":"),
        )
    )
if __name__ == "__main__":
    main()
