#!/usr/bin/env python3
"""Phase 23 — constrained minisuperspace rigging-map density control.

This executable calibrates the next step after the finite-mode density of
Phase 22.  It uses one hyperbolic constraint C=p_T^2-h, derives full-real-lapse
rigging kernels, separates them from half-lapse Green functions, and fixes an
explicit positive-frequency clock orientation.  On a compact Dirichlet
spectral regulator it then constructs the trace-class density generated by
B_L=exp(-L sqrt(h)) and checks its two-sheet purification.

The calculation also exposes three obstructions: an equal-branch real WDW
state has zero signed Klein--Gordon norm, a positive-frequency superposition
can have locally negative current density even when its integrated physical
norm is positive, and a quadratic zero-frequency root makes the rigging
Jacobian singular.  Removing the compact regulator also destroys trace class.

This is an exact 1+1-dimensional KG-type minisuperspace calibration.  The
compact interval, branch choice, preparation length L, and toy anti-linear
pairing are supplied inputs.  It is not the closed Starobinsky WDW operator,
a complex-cap path integral, a spacetime Pin lift, or a gauge-fixed local-
supergravity BRST density.  The program writes no files.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field

import numpy as np
import sympy as sp
from scipy.integrate import quad


@dataclass
class Audit:
    exact_passed: int = 0
    numerical_passed: int = 0
    exact_ids: list[str] = field(default_factory=list)
    numerical_ids: list[str] = field(default_factory=list)
    exact_records: list[dict[str, str]] = field(default_factory=list)
    numerical_records: list[dict[str, str]] = field(default_factory=list)

    def exact(self, check_id: str, condition: bool, statement: str) -> None:
        self._check_unique(check_id)
        if not condition:
            raise AssertionError(f"[FAIL] {check_id}: {statement}")
        self.exact_passed += 1
        self.exact_ids.append(check_id)
        self.exact_records.append(
            {"id": check_id, "status": "PASS", "statement": statement}
        )
        print(f"[PASS] {check_id}: {statement}")

    def numerical(self, check_id: str, condition: bool, statement: str) -> None:
        self._check_unique(check_id)
        if not condition:
            raise AssertionError(f"[NUMERIC FAIL] {check_id}: {statement}")
        self.numerical_passed += 1
        self.numerical_ids.append(check_id)
        self.numerical_records.append(
            {"id": check_id, "status": "PASS", "statement": statement}
        )
        print(f"[NUMERIC PASS] {check_id}: {statement}")

    def _check_unique(self, check_id: str) -> None:
        if check_id in self.exact_ids or check_id in self.numerical_ids:
            raise AssertionError(f"[FAIL] duplicate check id: {check_id}")


def exact_zero(expression: sp.Expr | sp.MatrixBase) -> bool:
    if isinstance(expression, sp.MatrixBase):
        return (
            expression.applyfunc(
                lambda entry: sp.simplify(
                    sp.expand_complex(entry.rewrite(sp.exp))
                )
            ).is_zero_matrix
            is True
        )
    return (
        sp.simplify(sp.factor(sp.expand_complex(expression.rewrite(sp.exp))))
        == 0
    )


def rigging_and_lapse_controls(audit: Audit) -> dict[str, object]:
    spectral_c = sp.symbols("c", real=True, finite=True)
    epsilon, lapse = sp.symbols("epsilon N", positive=True, finite=True, real=True)

    positive_half_transform = 1 / (epsilon - sp.I * spectral_c)
    negative_half_transform = 1 / (epsilon + sp.I * spectral_c)
    abel_from_lapse = sp.simplify(
        (positive_half_transform + negative_half_transform) / (2 * sp.pi)
    )
    abel_kernel = epsilon / (
        sp.pi * (spectral_c**2 + epsilon**2)
    )
    audit.exact(
        "P23.rigging.full_real_lapse_abel_kernel",
        exact_zero(abel_from_lapse - abel_kernel),
        "full real lapse with exp(-epsilon|N|) gives epsilon/[pi(C^2+epsilon^2)]",
    )
    audit.exact(
        "P23.rigging.abel_delta_normalization",
        exact_zero(
            sp.integrate(abel_kernel, (spectral_c, -sp.oo, sp.oo)) - 1
        ),
        "the Abel rigging kernel has unit spectral integral",
    )

    gaussian_from_lapse = sp.simplify(
        (2 * sp.sqrt(sp.pi) / epsilon)
        * sp.exp(-spectral_c**2 / epsilon**2)
        / (2 * sp.pi)
    )
    gaussian_kernel = sp.exp(-spectral_c**2 / epsilon**2) / (
        sp.sqrt(sp.pi) * epsilon
    )
    audit.exact(
        "P23.rigging.full_real_lapse_gaussian_kernel",
        exact_zero(gaussian_from_lapse - gaussian_kernel),
        "Gaussian-damped full lapse gives exp(-C^2/epsilon^2)/(sqrt(pi)epsilon)",
    )

    width, momentum = sp.symbols(
        "lambda p", positive=True, finite=True, real=True
    )
    h_c = sp.exp(-spectral_c**2 / (2 * width**2)) / (
        sp.pi * width**2
    ) ** sp.Rational(1, 4)
    u_p = sp.exp(-momentum**2 / (2 * width**2)) / (
        sp.pi * width**2
    ) ** sp.Rational(1, 4)
    kinematical_norm = sp.integrate(
        h_c**2, (spectral_c, -sp.oo, sp.oo)
    ) * sp.integrate(u_p**2, (momentum, -sp.oo, sp.oo))
    audit.exact(
        "P23.rigging.kinematical_gaussian_norm",
        exact_zero(kinematical_norm - 1),
        "the factorized kinematical Gaussian seed has auxiliary L2 norm one",
    )

    regulated_seed_norm = sp.integrate(
        h_c**2 * gaussian_kernel, (spectral_c, -sp.oo, sp.oo)
    )
    regulated_seed_target = 1 / (
        sp.sqrt(sp.pi) * sp.sqrt(width**2 + epsilon**2)
    )
    audit.exact(
        "P23.rigging.regulated_seed_norm",
        exact_zero(regulated_seed_norm - regulated_seed_target),
        "the regulated rigging norm is 1/[sqrt(pi)sqrt(lambda^2+epsilon^2)]",
    )

    shell_norm = sp.limit(regulated_seed_norm, epsilon, 0, dir="+")
    normalized_shell_profile_factor = sp.simplify(
        h_c.subs(spectral_c, 0) / sp.sqrt(shell_norm)
    )
    audit.exact(
        "P23.rigging.normalized_shell_profile",
        exact_zero(normalized_shell_profile_factor - 1),
        "after rigging normalization the on-shell seed reduces to the chosen physical profile",
    )

    audit.exact(
        "P23.rigging.not_a_bounded_kinematical_projector",
        sp.limit(gaussian_kernel.subs(spectral_c, 0), epsilon, 0, dir="+")
        == sp.oo,
        "the approximate delta has divergent operator supremum and is not an ordinary bounded projector",
    )

    half_lapse = positive_half_transform
    audit.exact(
        "P23.rigging.half_lapse_is_resolvent",
        exact_zero((epsilon - sp.I * spectral_c) * half_lapse - 1),
        "the positive half-lapse integral is a resolvent Green function",
    )
    audit.exact(
        "P23.rigging.half_lapse_is_not_projector_kernel",
        not exact_zero(
            half_lapse - half_lapse.subs(spectral_c, -spectral_c)
        ),
        "the half-lapse kernel is not even in C and therefore is not the full rigging delta",
    )

    positive_euclidean_time, negative_eigenvalue = sp.symbols(
        "s c_abs", positive=True, finite=True, real=True
    )
    audit.exact(
        "P23.rigging.naive_euclidean_lapse_mutant_diverges",
        sp.limit(
            sp.exp(positive_euclidean_time * negative_eigenvalue),
            positive_euclidean_time,
            sp.oo,
        )
        == sp.oo,
        "exp(-sC) diverges on the negative spectrum of a hyperbolic constraint",
    )

    return {
        "constraint_spectral_coordinate": "c",
        "full_lapse_Abel_kernel": "epsilon/[pi(c^2+epsilon^2)]",
        "full_lapse_Gaussian_kernel": "exp(-c^2/epsilon^2)/(sqrt(pi)epsilon)",
        "seed_width": "lambda",
        "regulated_seed_norm": "1/[sqrt(pi)sqrt(lambda^2+epsilon^2)]",
        "half_lapse": "1/(epsilon-i c), a resolvent rather than a projector",
        "warning": (
            "the rigging map is distributional; finite-regulator kernels and "
            "ordinary kinematical traces are not physical density matrices"
        ),
    }


def mass_shell_and_current_controls(audit: Audit) -> dict[str, object]:
    mode_number = sp.symbols("n", integer=True, positive=True)
    momentum_t = sp.symbols("p_T", real=True, finite=True)
    mass = sp.symbols("mu", positive=True, finite=True, real=True)
    clock, coordinate = sp.symbols("T q", real=True, finite=True)
    energy = sp.sqrt(mode_number**2 + mass**2)
    constraint = momentum_t**2 - energy**2

    audit.exact(
        "P23.constraint.dirichlet_spectrum",
        exact_zero(energy**2 - mode_number**2 - mass**2),
        "on q in (0,pi), h=-d_q^2+mu^2 has E_n^2=n^2+mu^2",
    )
    audit.exact(
        "P23.constraint.frequency_roots",
        exact_zero(constraint.subs(momentum_t, energy))
        and exact_zero(constraint.subs(momentum_t, -energy)),
        "the quadratic constraint has positive and negative simple roots",
    )

    derivative = sp.diff(constraint, momentum_t)
    positive_shell_weight = sp.simplify(
        1 / derivative.subs(momentum_t, energy)
    )
    negative_shell_weight = sp.simplify(
        -1 / derivative.subs(momentum_t, -energy)
    )
    audit.exact(
        "P23.constraint.delta_shell_jacobian",
        exact_zero(positive_shell_weight - 1 / (2 * energy))
        and exact_zero(negative_shell_weight - 1 / (2 * energy)),
        "delta(C) gives 1/(2E_n) on each simple root",
    )
    audit.exact(
        "P23.constraint.clock_gauge_FP_cancellation",
        exact_zero(2 * energy * positive_shell_weight - 1),
        "the T=tau clock-gauge determinant 2E_n cancels the shell Jacobian",
    )

    spatial_mode = sp.sqrt(2 / sp.pi) * sp.sin(mode_number * coordinate)
    positive_mode = (
        spatial_mode
        * sp.exp(-sp.I * energy * clock)
        / sp.sqrt(2 * energy)
    )
    negative_mode = (
        spatial_mode
        * sp.exp(sp.I * energy * clock)
        / sp.sqrt(2 * energy)
    )

    def wdw_residual(mode: sp.Expr) -> sp.Expr:
        return sp.simplify(
            -sp.diff(mode, clock, 2)
            + sp.diff(mode, coordinate, 2)
            - mass**2 * mode
        )

    def clock_current(mode: sp.Expr) -> sp.Expr:
        return sp.simplify(
            sp.I
            * (
                sp.conjugate(mode) * sp.diff(mode, clock)
                - sp.diff(sp.conjugate(mode), clock) * mode
            )
        )

    audit.exact(
        "P23.WDW.frequency_modes_solve_constraint",
        exact_zero(wdw_residual(positive_mode))
        and exact_zero(wdw_residual(negative_mode)),
        "both normalized frequency modes solve the regulated KG-type WDW equation",
    )
    positive_integrated_current = sp.integrate(
        clock_current(positive_mode), (coordinate, 0, sp.pi)
    )
    negative_integrated_current = sp.integrate(
        clock_current(negative_mode), (coordinate, 0, sp.pi)
    )
    audit.exact(
        "P23.current.integrated_frequency_signs",
        exact_zero(positive_integrated_current - 1)
        and exact_zero(negative_integrated_current + 1),
        "the integrated KG current is +1 on the chosen branch and -1 on its conjugate",
    )

    relative_phase = sp.symbols("theta", real=True, finite=True)
    coefficient_plus = 1 / sp.sqrt(2)
    coefficient_minus = sp.exp(sp.I * relative_phase) / sp.sqrt(2)
    induced_branch_norm = sp.simplify(
        coefficient_plus * sp.conjugate(coefficient_plus)
        + coefficient_minus * sp.conjugate(coefficient_minus)
    )
    signed_branch_current = sp.simplify(
        coefficient_plus * sp.conjugate(coefficient_plus)
        - coefficient_minus * sp.conjugate(coefficient_minus)
    )
    phase_zero_pi_overlap = sp.simplify(
        sp.Rational(1, 2) * (1 + sp.exp(sp.I * sp.pi))
    )
    audit.exact(
        "P23.current.induced_sum_vs_signed_difference",
        exact_zero(induced_branch_norm - 1)
        and exact_zero(signed_branch_current)
        and exact_zero(phase_zero_pi_overlap),
        "a nontrivial equal-weight phase family has unit induced norm while its signed KG current cancels",
    )

    massless_two_mode = (
        sp.sin(coordinate) * sp.exp(-sp.I * clock)
        + sp.sin(2 * coordinate) * sp.exp(-2 * sp.I * clock)
    ) / sp.sqrt(3 * sp.pi)
    density_current = clock_current(massless_two_mode)
    spatial_current = sp.simplify(
        sp.I
        * (
            sp.conjugate(massless_two_mode)
            * sp.diff(massless_two_mode, coordinate)
            - sp.diff(sp.conjugate(massless_two_mode), coordinate)
            * massless_two_mode
        )
    )
    continuity = sp.simplify(
        sp.expand_complex(
            sp.diff(density_current, clock)
            - sp.diff(spatial_current, coordinate)
        )
    )
    audit.exact(
        "P23.current.two_mode_continuity",
        exact_zero(continuity),
        "the two-mode positive-frequency current obeys d_T j_T-d_q j_q=0",
    )
    integrated_two_mode_current = sp.integrate(
        density_current, (coordinate, 0, sp.pi)
    )
    two_mode_coefficients = sp.Matrix([1, sp.sqrt(2)]) / sp.sqrt(3)
    two_mode_density = sp.simplify(
        two_mode_coefficients * two_mode_coefficients.H
    )
    audit.exact(
        "P23.current.integrated_density_equals_trace",
        exact_zero(integrated_two_mode_current - sp.trace(two_mode_density))
        and exact_zero(sp.trace(two_mode_density) - 1),
        "the integrated physical current equals the unit trace of the two-mode density",
    )

    negative_point = sp.acos(-sp.Rational(3, 8))
    negative_current_value = sp.simplify(
        density_current.subs({clock: 0, coordinate: negative_point})
    )
    audit.exact(
        "P23.current.local_density_not_pointwise_positive",
        exact_zero(negative_current_value + 55 / (768 * sp.pi))
        and negative_current_value.is_negative is True,
        "a positive-frequency superposition has j_T=-55/(768pi) at the recorded point",
    )

    return {
        "regulator": "q in (0,pi) with Dirichlet modes sqrt(2/pi)sin(nq)",
        "spectrum": "E_n=sqrt(n^2+mu^2), n>=1",
        "constraint": "C=p_T^2-E_n^2",
        "physical_branch": "explicit positive-frequency and T-clock orientation",
        "two_mode_current": {
            "state": "[sin(q)e^-iT+sin(2q)e^-2iT]/sqrt(3pi)",
            "integrated_current": "1",
            "negative_local_value": "-55/(768pi)",
        },
        "warning": (
            "the integrated branch inner product is positive; the local current "
            "density need not be pointwise positive"
        ),
    }


def trace_class_density_controls(audit: Audit) -> dict[str, object]:
    mode_number = sp.symbols("n", integer=True, positive=True)
    mass, length = sp.symbols(
        "mu L", positive=True, finite=True, real=True
    )
    energy = sp.sqrt(mode_number**2 + mass**2)
    positive_gap_witness = mass**2 / (energy + mode_number)

    audit.exact(
        "P23.density.spectral_comparison_gap",
        exact_zero(energy**2 - mode_number**2 - mass**2)
        and exact_zero(energy - mode_number - positive_gap_witness)
        and positive_gap_witness.is_positive is True,
        "E_n>n for mu>0, so exp(-2LE_n) is bounded by exp(-2Ln)",
    )
    # Write exp(-2L)=1/(1+u), u=exp(2L)-1>0.  This makes the
    # convergence witness assumption-explicit instead of asking SymPy to infer
    # an inequality through a symbolic exponential.
    positive_u = sp.symbols("u", positive=True, finite=True, real=True)
    geometric_ratio = 1 / (1 + positive_u)
    geometric_bound = sp.simplify(geometric_ratio / (1 - geometric_ratio))
    audit.exact(
        "P23.density.trace_class_geometric_bound",
        exact_zero(geometric_bound - 1 / positive_u)
        and geometric_bound.is_positive is True
        and geometric_bound.is_finite is True,
        "Tr exp(-2L sqrt(h)) converges by comparison with 1/(exp(2L)-1)",
    )

    energies = [sp.sqrt(index**2 + mass**2) for index in (1, 2, 3)]
    weights = [sp.exp(-length * value) for value in energies]
    z_three = sp.simplify(sum(value**2 for value in weights))
    paired_state = sp.zeros(9, 1)
    for index, value in enumerate(weights):
        paired_state[3 * index + index, 0] = value / sp.sqrt(z_three)
    pure_density = sp.simplify(paired_state * paired_state.H)
    audit.exact(
        "P23.density.truncated_purification",
        exact_zero((paired_state.H * paired_state)[0] - 1)
        and exact_zero(pure_density - pure_density.H)
        and exact_zero(pure_density**2 - pure_density)
        and pure_density.rank() == 1,
        "the three-level spectral truncation is a normalized pure two-sheet purification",
    )

    coefficient_matrix = sp.diag(*weights) / sp.sqrt(z_three)
    reduced_density = sp.simplify(coefficient_matrix * coefficient_matrix.H)
    audit.exact(
        "P23.density.partial_trace_positive",
        exact_zero(sp.trace(reduced_density) - 1)
        and reduced_density.rank() == 3
        and all(entry.is_positive is True for entry in reduced_density.diagonal()),
        "the reduced spectral density is positive, finite rank, and unit trace",
    )
    spectral_generator = sp.diag(*energies)
    audit.exact(
        "P23.density.spectral_stationarity",
        exact_zero(spectral_generator * reduced_density - reduced_density * spectral_generator),
        "the reduced density commutes with A=sqrt(h) in the regulated spectral basis",
    )

    ratio_21 = sp.simplify(reduced_density[1, 1] / reduced_density[0, 0])
    ratio_target = sp.exp(-2 * length * (energies[1] - energies[0]))
    audit.exact(
        "P23.density.bridge_weight_ratio",
        exact_zero(ratio_21 - ratio_target),
        "B_L=exp(-L sqrt(h)) fixes the two-level ratio once L and h are supplied",
    )

    profile_parity = sp.diag(1, -1, 1)
    sheet_swap = sp.zeros(9, 9)
    for left in range(3):
        for right in range(3):
            sheet_swap[3 * right + left, 3 * left + right] = 1
    theta_linear = sheet_swap * sp.kronecker_product(
        profile_parity, profile_parity
    )
    audit.exact(
        "P23.theta.toy_pairing",
        theta_linear * theta_linear.conjugate() == sp.eye(9)
        and exact_zero(theta_linear * paired_state.conjugate() - paired_state),
        "the regulated spectral state is invariant under the toy parity-sheet anti-linear pairing",
    )

    ratio_derivative = sp.factor(sp.diff(sp.log(ratio_target), length))
    spectral_gap_21 = sp.simplify(3 / (energies[1] + energies[0]))
    audit.exact(
        "P23.selection.preparation_length_remains_input",
        exact_zero(energies[1] - energies[0] - spectral_gap_21)
        and spectral_gap_21.is_positive is True
        and exact_zero(ratio_derivative + 2 * spectral_gap_21),
        "the physical weights vary continuously with the supplied preparation length L",
    )

    return {
        "physical_generator": "A=sqrt(h)",
        "relational_bridge_input": "B_L=exp(-L A), L>0",
        "partition": "Z_L=sum_(n>=1) exp(-2L sqrt(n^2+mu^2))",
        "state": "Z_L^-1/2 sum_n exp(-L E_n)|n>_L tensor Theta|n>_R",
        "reduced_density": "rho_plus=Z_L^-1 exp(-2L A)",
        "trace_class_reason": "E_n>n gives a convergent geometric upper bound",
        "warning": (
            "L, the compact regulator, the branch pairing, and Theta are inputs; "
            "B_L is not derived here from the Starobinsky cap"
        ),
    }


def zero_root_and_regulator_controls(audit: Audit) -> dict[str, object]:
    epsilon, momentum_t = sp.symbols(
        "epsilon p_T", positive=True, finite=True, real=True
    )
    quartic_coordinate = sp.symbols("y", real=True, finite=True)
    quartic_unit_integral = sp.integrate(
        1 / (quartic_coordinate**4 + 1),
        (quartic_coordinate, -sp.oo, sp.oo),
    )
    zero_root_integral = sp.simplify(
        quartic_unit_integral / (sp.pi * sp.sqrt(epsilon))
    )
    audit.exact(
        "P23.zero_root.quadratic_root_divergence",
        exact_zero(zero_root_integral - 1 / sp.sqrt(2 * epsilon))
        and sp.limit(zero_root_integral, epsilon, 0, dir="+") == sp.oo,
        "at E=0 the quadratic-root rigging integral diverges as 1/sqrt(2epsilon)",
    )
    audit.exact(
        "P23.zero_root.clock_FP_vanishes",
        exact_zero((2 * momentum_t).subs(momentum_t, 0)),
        "the intrinsic T-clock Faddeev--Popov determinant vanishes at the double root",
    )

    linear_constraint = sp.symbols("C_lin", real=True, finite=True)
    linear_root_jacobian = sp.diff(linear_constraint, linear_constraint)
    audit.exact(
        "P23.zero_root.linear_constraint_control",
        linear_root_jacobian == 1,
        "a linear p_T-A constraint has a simple unit Jacobian but preselects time orientation",
    )

    length, box_radius = sp.symbols(
        "L R", positive=True, finite=True, real=True
    )
    massless_box_partition = 1 / (sp.exp(2 * length / box_radius) - 1)
    audit.exact(
        "P23.regulator.decompactification_not_trace_class",
        sp.limit(massless_box_partition, box_radius, sp.oo) == sp.oo
        and sp.limit(
            2 * length * massless_box_partition / box_radius,
            box_radius,
            sp.oo,
        )
        == 1,
        "the massless box partition diverges as R/(2L) in the decompactification limit",
    )

    return {
        "spectral_zero_root": "E=0 gives a double root of p_T^2-E^2",
        "zero_root_integral": "1/sqrt(2epsilon)",
        "zero_root_FP": "2E=0",
        "linear_control": "C_lin=p_T-A is regular but chooses an orientation",
        "decompactification": "Z_R~R/(2L) for the massless Dirichlet spectrum",
        "warning": (
            "a cap Hessian zero mode would additionally require a genuine saddle "
            "family, primed determinant, collective-coordinate Jacobian, and modulus measure"
        ),
    }


def numerical_controls(audit: Audit) -> dict[str, object]:
    width = 0.7
    epsilon = 0.02
    analytic_seed_norm = 1.0 / (
        np.sqrt(np.pi) * np.sqrt(width**2 + epsilon**2)
    )

    def seed_integrand(value: float) -> float:
        h_squared = np.exp(-(value / width) ** 2) / (
            np.sqrt(np.pi) * width
        )
        delta_epsilon = np.exp(-(value / epsilon) ** 2) / (
            np.sqrt(np.pi) * epsilon
        )
        return float(h_squared * delta_epsilon)

    numeric_seed_norm, _ = quad(
        seed_integrand,
        -8 * width,
        8 * width,
        epsabs=1e-12,
        epsrel=1e-12,
        points=[0.0],
        limit=400,
    )
    seed_relative_error = abs(numeric_seed_norm / analytic_seed_norm - 1)
    audit.numerical(
        "P23.numeric.regulated_seed_norm",
        seed_relative_error < 1e-10,
        f"Gaussian rigging norm matches the exact value; relative error={seed_relative_error:.3e}",
    )

    def spectral_sum(cutoff: int) -> float:
        indices = np.arange(1, cutoff + 1, dtype=float)
        return float(np.exp(-2 * np.sqrt(indices**2 + 1)).sum())

    z16 = spectral_sum(16)
    z64 = spectral_sum(64)
    z256 = spectral_sum(256)
    convergence_error = max(abs(z64 - z16), abs(z256 - z64))
    audit.numerical(
        "P23.numeric.trace_sum_convergence",
        convergence_error < 2e-12,
        f"mu=L=1 spectral sums converge to {z256:.15f}; max recorded increment={convergence_error:.3e}",
    )

    density = np.array(
        [[1.0 / 3.0, np.sqrt(2.0) / 3.0],
         [np.sqrt(2.0) / 3.0, 2.0 / 3.0]],
        dtype=float,
    )
    eigenvalues = np.linalg.eigvalsh(density)
    audit.numerical(
        "P23.numeric.two_mode_density_spectrum",
        np.allclose(eigenvalues, np.array([0.0, 1.0]), atol=1e-14)
        and abs(np.trace(density) - 1) < 1e-14,
        f"two-mode pure density eigenvalues are {eigenvalues.tolist()} and trace is one",
    )

    grid = np.linspace(0.0, np.pi, 20001)
    current_errors: list[float] = []
    for time_value in (0.0, 0.3, 1.1, 2.7):
        wave = (
            np.sin(grid) * np.exp(-1j * time_value)
            + np.sin(2 * grid) * np.exp(-2j * time_value)
        ) / np.sqrt(3 * np.pi)
        time_derivative = (
            -1j * np.sin(grid) * np.exp(-1j * time_value)
            - 2j * np.sin(2 * grid) * np.exp(-2j * time_value)
        ) / np.sqrt(3 * np.pi)
        current = 1j * (
            np.conjugate(wave) * time_derivative
            - np.conjugate(time_derivative) * wave
        )
        integral = float(np.trapezoid(np.real(current), grid))
        current_errors.append(abs(integral - 1))
    max_current_error = max(current_errors)
    audit.numerical(
        "P23.numeric.current_slice_conservation",
        max_current_error < 5e-13,
        f"integrated current stays one on four time slices; max error={max_current_error:.3e}",
    )

    return {
        "rigging_seed": {
            "lambda": width,
            "epsilon": epsilon,
            "relative_error": seed_relative_error,
        },
        "trace_sum": {
            "mu": 1.0,
            "L": 1.0,
            "Z_16": z16,
            "Z_64": z64,
            "Z_256": z256,
            "max_increment": convergence_error,
        },
        "density_eigenvalues": eigenvalues.tolist(),
        "current_max_slice_error": max_current_error,
    }


def run() -> dict[str, object]:
    audit = Audit()
    rigging = rigging_and_lapse_controls(audit)
    mass_shell = mass_shell_and_current_controls(audit)
    density = trace_class_density_controls(audit)
    zero_root = zero_root_and_regulator_controls(audit)
    numerics = numerical_controls(audit)

    result: dict[str, object] = {
        "phase": "P23",
        "calculation": "constrained minisuperspace rigging-map density control",
        "exact_checks": audit.exact_passed,
        "numerical_checks": audit.numerical_passed,
        "exact_check_ids": audit.exact_ids,
        "numerical_check_ids": audit.numerical_ids,
        "exact_check_records": audit.exact_records,
        "numerical_check_records": audit.numerical_records,
        "rigging_and_lapse": rigging,
        "mass_shell_and_current": mass_shell,
        "trace_class_density": density,
        "zero_root_and_regulator": zero_root,
        "numerical_controls": numerics,
        "claim_status": {
            "full_real_lapse_average_defines_a_distributional_rigging_map": "SUPPORTED_IN_SINGLE_CONSTRAINT_CONTROL",
            "after_explicit_clock_and_positive_frequency_choice_the_integrated_norm_is_positive": "SUPPORTED_IN_REGULATED_KG_CONTROL",
            "imposed_B_L_defines_a_positive_trace_class_regulated_density": "SUPPORTED_AT_FINITE_COMPACT_REGULATOR",
            "positive_frequency_local_current_is_pointwise_positive": "CONTRADICTED_BY_EXACT_TWO_MODE_WITNESS",
            "CPT_reality_and_zero_signed_current_uniquely_select_a_density": "CONTRADICTED_IN_THIS_CONTROL",
            "regulated_density_has_a_trace_class_decompactification_limit": "CONTRADICTED_IN_MASSLESS_BOX_CONTROL",
            "closed_Starobinsky_complex_cap_derives_L_and_the_density": "OPEN_NOT_COMPUTED",
            "gauge_fixed_local_SUGRA_BRST_seam_density_exists": "OPEN_NOT_COMPUTED",
        },
        "scope_guard": {
            "what_is_computed": [
                "one hyperbolic single-constraint rigging-map calibration",
                "full-real-lapse Abel and Gaussian delta sequences",
                "one explicit T clock and positive-frequency branch choice",
                "q in (0,pi) Dirichlet spectral regulator with E_n=sqrt(n^2+mu^2)",
                "the imposed bridge B_L=exp(-L sqrt(h)) at L>0",
                "an infinite-rank positive trace-class spectral density at finite regulator",
                "integrated and local two-mode KG current controls",
                "quadratic E=0 root and decompactification obstructions",
            ],
            "what_is_not_computed": [
                "the closed k=+1 Starobinsky or Cecotti Wheeler-DeWitt operator",
                "a regular complex cap, Picard-Lefschetz contour, or cap-derived L",
                "factor-ordering, constraint-rescaling, and clock-patch independence",
                "a regulator-independent WDW Born probability over universe initial data",
                "a 4d Clifford or Pin lift",
                "gravitino, Goldstino, three-form, membrane, or ghost sectors",
                "local-SUGRA constraints or BRST cohomology",
                "a selected flux n, inflaton phi0, curvature radius, or SUSY-breaking scale",
            ],
        },
        "obstruction_guards": [
            {
                "id": "P23.guard.rigging_map_is_not_bounded_projector",
                "target": "ordinary bounded kinematical projector from delta(C)",
                "observed_status": "EXPECTED_OBSTRUCTION_CONFIRMED",
                "supporting_check_ids": [
                    "P23.rigging.not_a_bounded_kinematical_projector",
                    "P23.rigging.half_lapse_is_resolvent",
                ],
                "scope": "the recorded noncompact single-constraint spectral average",
            },
            {
                "id": "P23.guard.zero_current_is_not_unique_positive_density",
                "target": "unique positive density from CPT reality plus zero signed WDW current",
                "observed_status": "EXPECTED_OBSTRUCTION_CONFIRMED",
                "supporting_check_ids": [
                    "P23.current.induced_sum_vs_signed_difference",
                    "P23.current.local_density_not_pointwise_positive",
                    "P23.selection.preparation_length_remains_input",
                ],
                "scope": "the regulated KG-type minisuperspace and signed-current prescription",
            },
            {
                "id": "P23.guard.quadratic_zero_root",
                "target": "simple-root clock gauge at E=0",
                "observed_status": "EXPECTED_OBSTRUCTION_CONFIRMED",
                "supporting_check_ids": [
                    "P23.zero_root.quadratic_root_divergence",
                    "P23.zero_root.clock_FP_vanishes",
                ],
                "scope": "the quadratic p_T^2-E^2 constraint at its double root",
            },
        ],
        "next_calculation": {
            "homogeneous_sector": (
                "replace the compact normal form and supplied L by the actual closed "
                "Starobinsky complex-cap constraint, extrinsic/two-patch clock or "
                "deparametrization-free RAQ, factor ordering, primed determinant, "
                "collective-coordinate Jacobian, and physical current"
            ),
            "local_sugra_sector": (
                "only after that, derive the coupled gauge-fixed gravitino-Goldstino-"
                "ghost boundary operator and test the projected density"
            ),
        },
    }
    print("PHASE23_RESULT=" + json.dumps(result, sort_keys=True))
    return result


if __name__ == "__main__":
    run()
